# Generated by Django 4.0.3 on 2022-08-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pt_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pt_name',
        ),
        migrations.AlterField(
            model_name='staff',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store', verbose_name='部門'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部門'),
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='検査機器')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store', verbose_name='部門')),
            ],
        ),
    ]
