# Generated by Django 4.0.3 on 2022-08-26 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_booking_pt_id_remove_booking_pt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pt_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='ID'),
        ),
    ]
