# Generated by Django 4.1.1 on 2022-10-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_patient_pt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='modality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.modality', verbose_name='モダリティ'),
            preserve_default=False,
        ),
    ]
