# Generated by Django 4.1.1 on 2022-10-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_modality_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.modality', verbose_name='モダリティ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff', verbose_name='スタッフ'),
        ),
    ]
