# Generated by Django 4.1.1 on 2022-10-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_parentcategory_post_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt_data', to='app.category', verbose_name='部位'),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default=3, max_length=20, verbose_name='タイトル'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
