# Generated by Django 4.1.1 on 2022-11-10 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_booking_category_remove_booking_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.remark', verbose_name='備考'),
        ),
    ]
