# Generated by Django 4.1.1 on 2022-12-15 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remark_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='カテゴリ'),
        ),
    ]
