# Generated by Django 4.1.1 on 2022-12-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_remark_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='orders',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.remark', verbose_name='備考'),
        ),
    ]
