# Generated by Django 4.1.1 on 2022-12-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_remark_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='order_remarks',
            field=models.CharField(default=4, max_length=255, verbose_name='備考'),
            preserve_default=False,
        ),
    ]
