# Generated by Django 4.1.1 on 2022-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_remark_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='order_remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
    ]
