# Generated by Django 4.1.1 on 2023-01-06 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_remark_order_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='開始時間'),
        ),
    ]
