# Generated by Django 4.1.1 on 2023-01-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_booking_date_alter_booking_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='parts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='検査部位'),
        ),
    ]
