# Generated by Django 4.1.1 on 2023-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_remark_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
